version: '3.7'

services:
  openldap:
    container_name: openldap_ldap
    image: docker.io/bitnami/openldap:2.6
    ports:
      - 1389:1389
      - 1636:1636
    environment:
      - LDAP_ROOT=dc=unud,dc=ac,dc=id
      - LDAP_ADMIN_USERNAME=admin
      - LDAP_ADMIN_PASSWORD=adminpassword
      - LDAP_ADD_SCHEMAS=yes
      - LDAP_EXTRA_SCHEMAS="cosine,inetorgperson,nis,unudperson"
    volumes:
      - openldap_data:/bitnami/openldap
      - ./tmp:/tmp/bitnami
      - ./schemas/unudperson.schema:/opt/bitnami/openldap/etc/schema/unudperson.schema
      - ./schemas/unudperson.ldif:/opt/bitnami/openldap/etc/schema/unudperson.ldif

volumes:
  openldap_data:
    driver: local